### ISSUE TITLE
Control center and keyboard language bubbles bugged in Windows 11

### ISSUE THREAD

**Issue by guidolamanna** [Droptop-Four/Update#1]
I have Windows 11 currently installed and the new control center bubble, as well as the keyboard language bubble are cut in the top (as shown in the pictures below). This only happens when Droptop's setting is on "always show". This doesn't happen with the notification bubble. It would be amazing if you fix this issue for the next update. Thanks.

![Screenshot (80)](https://user-images.githubusercontent.com/95378894/144309936-29ee6cf5-802e-42d4-92bc-c779c9e5aaa4.jpg)

![Screenshot (81)](https://user-images.githubusercontent.com/95378894/144309945-119cb7f6-4f25-4dd9-888b-c28a4842a920.jpg)

**Comment by 66Bunz** [comment]
@guidolamanna Hey Guido, sorry for the late reply!
This problem you are showing is a win11 bug, and nothing can be done until Microsoft fixes it.
