### ISSUE TITLE
Album art not being displayed in Volume app after installing update

### ISSUE THREAD

**Issue by jamimanasir98** [Droptop-Four/Update#11]
The album art won't show up anymore in the Volume App for any browser based media or from the spotify app. It was working before installing the update.
![image](https://user-images.githubusercontent.com/119537328/224508933-8204ae7e-92c0-4493-9326-f85395e6916c.png)
At first I though there's issue with the WebNowPlaying plugin I had installed for my spotify. But then I noticed the issue is with browser based media as well. Is there something I have done wrong while installing the update. Please let me know. Thanks!

**Comment by 66Bunz** [comment]
@jamimanasir98 this issue should now be solved
