### ISSUE TITLE
Downloading and installing JaxCore app does not do anything

### ISSUE THREAD

**Issue by Ast3r0ids** [Droptop-Four/Update#3]
I have checked in the community apps folder and on the bar as well, but I can't find the JaxCore App.

**Comment by notAperson535** [comment]
@Ast3r0ids  try restarting rainmeter

**Comment by Ast3r0ids** [comment]
I have tried this multiple times but it does not do anything

**Comment by notAperson535** [comment]
Go to droptop settings, then community apps and select one of the blank apps, and then select JaxCore

**Comment by notAperson535** [comment]
@66Bunz This should not be closed until we know it works for them
