### ISSUE TITLE
Audio devices not selecting the right device

### ISSUE THREAD

**Issue by VIXI0** [Droptop-Four/Update#4]
![image](https://user-images.githubusercontent.com/43118641/179755564-43eec135-e933-4ec9-8593-ef6dc8387660.png)
as you can see in the image above the audio device is not the one that I select: 
this is probably because is listing a Bluetooth devices that are not connected.

**Comment by 66Bunz** [comment]
With the last updates this issue should be solved, try to install the latest update!
