### ISSUE TITLE
App drawer is not working.

### ISSUE THREAD

**Issue by UdDReX** [Droptop-Four/Update#5]
Even after installing previous version and then again upgrading to the latest version, the App Drawer seem to not work. If it's something that is particular to me then can you suggest any solution? It would be a big help.

**Comment by 66Bunz** [comment]
If you are on win11 (there are some specific problems with the app drawer) and if you are not, join our [discord server](https://discord.gg/aGQ6uE4Fgp) because we have a couple of things you can try to solve this problems.
