### ISSUE TITLE
No Spotify option in preferred media player (supporter version)

### ISSUE THREAD

**Issue by evetech2021** [Droptop-Four/Update#6]
Droptop 4.308.2 supporter version doesn't have Spotify as a preferred media player option
![image](https://user-images.githubusercontent.com/105216764/190394561-528708e5-f10e-4151-97ac-356223de0232.png)

**Comment by 66Bunz** [comment]
That's because the plugin that was used to integrate spotify in droptop is being fixed, that option will return.
