### ISSUE TITLE
Droptop causing annoying open with popups

### ISSUE THREAD

**Issue by anmolsidhu1** [Droptop-Four/Update#9]
Since these recent updates, droptop is continuously causing these annoying popups to appear
![image](https://user-images.githubusercontent.com/116426097/210393601-54a510ed-e195-4790-9f75-8bfee4abb507.png)
![image](https://user-images.githubusercontent.com/116426097/210393622-a6956a9a-30e2-4048-8442-130204a2574c.png)
![image](https://user-images.githubusercontent.com/116426097/210393643-a68b2ee0-55be-4f21-8a61-790bea9eff31.png)
It appear on a continuous basis, please help

**Comment by 66Bunz** [comment]
It's a known bug, check our discord server to see when it'll be solved

**Comment by 66Bunz** [comment]
@anmolsidhu1 it should be now fixed, update Droptop
